<<<<<<< HEAD
on: [push, pull_request]

name: cwltool-validate

jobs:
  cwltool-validate:
    runs-on: ubuntu-latest
    container: hubentu/rcwl:latest

    steps:
      - uses: actions/checkout@v2
      - name: Rcwl-to-cwl-validate
        run: |
          library(RcwlPipelines)
          rfiles <- list.files("Rcwl", "*.R", full.names = TRUE)
          for(f in rfiles){
              tl <- cwlLoad(f)
              tl_n <- sub(".R$", "", basename(f))
              message("checking ", tl_n)
              tdir <- tempfile()
              writeCWL(tl, prefix = tl_n, outdir = tdir)
              re <- system(paste("cwltool --validate", file.path(tdir, paste0(tl_n, ".cwl"))), intern = TRUE)
              if(grepl("is valid CWL", re))message(paste(f, "is validated"))
          }
        shell: Rscript {0}
=======
on: [push, pull_request]

name: cwltool-validate

jobs:
  cwltool-validate:
    runs-on: ubuntu-latest
    container: 
      image: hubentu/rcwl:latest
      options: --user root
  
    steps:
      - uses: actions/checkout@v2
      - name: Rcwl-to-cwl-validate
        run: |
          library(RcwlPipelines)
          rfiles <- list.files("Rcwl", "tl*.R", full.names = TRUE)
          for(f in rfiles){
              tl <- cwlLoad(f)
              tl_n <- sub(".R$", "", basename(f))
              message("checking ", tl_n)
              tdir <- tempfile()
              writeCWL(tl, prefix = tl_n, outdir = tdir)
              re <- system(paste("cwltool --validate", file.path(tdir, paste0(tl_n, ".cwl"))), intern = TRUE)
              if(grepl("is valid CWL", re))message(paste(f, "is validated"))
          }
        shell: Rscript {0}
>>>>>>> c7c6ca1ff5298732610594b56bbc581a86140ca6
